package sec2;

public class UserException {

	public static void main(String[] args) {
		try {
			method1();
		} catch (RunException e) {
			
			//e.printStackTrace();
		}
		
	}
	public static void method1() throws RunException {
		throw new RunException("사용자 예외"); //throw:예외발생 객체 생성=자동예외발생
	}
}
